// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bktgkaoakhbipeawighy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdGdrYW9ha2hiaXBlYXdpZ2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzMxNzQsImV4cCI6MjA2NTYwOTE3NH0.9kavhypIXx32M_jVjVj1dZXK4G4e-luasvS8yOVyPEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);